### PR TITLE
Update `composer.json`

### PR DESCRIPTION
**Pull request by dbotelho**
Add support for both `Symfony 2.x` and `Symfony 3.0.x`

### CODE REVIEW

**Comment by dbotelho** [comment]
@gpaton Could you please review this PR so that I can use this project in Symfony3. Thanks

**Comment by gpaton** [comment]
Hello, why not use directly : `>= 2.1.*` ?

**Comment by dbotelho** [comment]
This one was more specific saying that it works for both sf2 and sf3 (but not for an sf4). But for the moment I don't see any issue with that. I've already updated.

**Comment by gpaton** [comment]
Good job, thank you

**Pull request merged**
